config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :teams
  devise_for :users
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/team.rb
class Team < ApplicationRecord
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.fetch(:project, {})
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]

  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.fetch(:team, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/home/index.html.erb
<div class="flex mt-16 justify-around">
    <div class="max-w-sm rounded overflow-hidden shadow-lg bg-red-200">
    <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">Assigned Tasks</div>
        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-pink-600 text-white rounded h-6 px-3 justify-center items-center">Assigned</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>

        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-pink-600 text-white rounded h-6 px-3 justify-center items-center">Assigned</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>

        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-pink-600 text-white rounded h-6 px-3 justify-center items-center">Assigned</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>

        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-pink-600 text-white rounded h-6 px-3 justify-center items-center">Assigned</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>
    </div>
    <div class="px-6 py-4">
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#photography</span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#travel</span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">#winter</span>
    </div>
    </div>



    <div class="max-w-sm rounded overflow-hidden shadow-lg bg-purple-200">
    
    <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">Tasks in Progress</div>

        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-purple-600 text-white rounded h-6 px-3 justify-center items-center">Progress</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>        

        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-purple-600 text-white rounded h-6 px-3 justify-center items-center">Progress</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>        

        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-purple-600 text-white rounded h-6 px-3 justify-center items-center">Progress</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>                
        
    </div>
    <div class="px-6 py-4">
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#photography</span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#travel</span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">#winter</span>
    </div>
    </div>



    <div class="max-w-sm rounded overflow-hidden shadow-lg bg-green-200">
    
    <div class="px-6 py-4">
        <div class="font-bold text-xl mb-2">Completed Tasks</div>

        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-green-600 text-white rounded h-6 px-3 justify-center items-center">Completed</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>      

        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-green-600 text-white rounded h-6 px-3 justify-center items-center">Completed</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>      

        <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded p-2 shadow text-teal text-sm mt-4">
            <span class="inline-flex bg-green-600 text-white rounded h-6 px-3 justify-center items-center">Completed</span>
            <span class="inline-flex px-2 text-gray-700">Donec sit amet neque risus. Pellentesque leo mauris, dictum et ligula in.</span>
        </div>      
    </div>
    <div class="px-6 py-4">
        <span class="inline-block bg-gray-200 rounded-full b-px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#photography</span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2">#travel</span>
        <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700">#winter</span>
    </div>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="bg-white shadow">
    <div class="container mx-auto px-4">
        <div class="flex items-center justify-between py-4">
        <div class="font-bold text-purple-600 main-logo-text">
            <a href="<%= root_path %>">PROJECT</a>
        </div>

        <div class="hidden sm:flex sm:items-center">
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mr-4">Products</a>
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mr-4">Marketplace</a>
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mr-4">Partners</a>
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600">Pricing</a>
        </div>

        <div class="hidden sm:flex sm:items-center">
            <% if current_user %>
                <a href="<%= edit_user_registration_path %>" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mr-4">My Accout</a>
                <a href="<%= destroy_user_session_path %>" data-method="delete" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-red-600 hover:border-purple-red">Log out</a>
            <% elsif %>
                <a href="<%= new_user_session_path %>" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mr-4">Sign in</a>
                <a href="<%= new_user_registration_path %>" class="text-gray-800 text-sm font-semibold border px-4 py-2 rounded-lg hover:text-purple-600 hover:border-purple-600">Sign up</a>
            <% end %>
            
        </div>

        <div class="sm:hidden cursor-pointer">
            <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-purple-600" viewBox="0 0 24 24">
            <path fill="currentColor" d="M12.9499909,17 C12.7183558,18.1411202 11.709479,19 10.5,19 C9.29052104,19 8.28164422,18.1411202 8.05000906,17 L3.5,17 C3.22385763,17 3,16.7761424 3,16.5 C3,16.2238576 3.22385763,16 3.5,16 L8.05000906,16 C8.28164422,14.8588798 9.29052104,14 10.5,14 C11.709479,14 12.7183558,14.8588798 12.9499909,16 L20.5,16 C20.7761424,16 21,16.2238576 21,16.5 C21,16.7761424 20.7761424,17 20.5,17 L12.9499909,17 Z M18.9499909,12 C18.7183558,13.1411202 17.709479,14 16.5,14 C15.290521,14 14.2816442,13.1411202 14.0500091,12 L3.5,12 C3.22385763,12 3,11.7761424 3,11.5 C3,11.2238576 3.22385763,11 3.5,11 L14.0500091,11 C14.2816442,9.85887984 15.290521,9 16.5,9 C17.709479,9 18.7183558,9.85887984 18.9499909,11 L20.5,11 C20.7761424,11 21,11.2238576 21,11.5 C21,11.7761424 20.7761424,12 20.5,12 L18.9499909,12 Z M9.94999094,7 C9.71835578,8.14112016 8.70947896,9 7.5,9 C6.29052104,9 5.28164422,8.14112016 5.05000906,7 L3.5,7 C3.22385763,7 3,6.77614237 3,6.5 C3,6.22385763 3.22385763,6 3.5,6 L5.05000906,6 C5.28164422,4.85887984 6.29052104,4 7.5,4 C8.70947896,4 9.71835578,4.85887984 9.94999094,6 L20.5,6 C20.7761424,6 21,6.22385763 21,6.5 C21,6.77614237 20.7761424,7 20.5,7 L9.94999094,7 Z M7.5,8 C8.32842712,8 9,7.32842712 9,6.5 C9,5.67157288 8.32842712,5 7.5,5 C6.67157288,5 6,5.67157288 6,6.5 C6,7.32842712 6.67157288,8 7.5,8 Z M16.5,13 C17.3284271,13 18,12.3284271 18,11.5 C18,10.6715729 17.3284271,10 16.5,10 C15.6715729,10 15,10.6715729 15,11.5 C15,12.3284271 15.6715729,13 16.5,13 Z M10.5,18 C11.3284271,18 12,17.3284271 12,16.5 C12,15.6715729 11.3284271,15 10.5,15 C9.67157288,15 9,15.6715729 9,16.5 C9,17.3284271 9.67157288,18 10.5,18 Z"/>
            </svg>
        </div>
        </div>
        
        <div class="block sm:hidden bg-white border-t-2 py-2">
        <div class="flex flex-col">
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mb-1">Products</a>
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mb-1">Marketplace</a>
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mb-1">Partners</a>
            <a href="#" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mb-1">Pricing</a>
            <div class="flex justify-between items-center border-t-2 pt-2">
            <a href="<%= new_user_session_path %>" class="text-gray-800 text-sm font-semibold hover:text-purple-600 mr-4">Sign in</a>
            <a href="<%= new_user_registration_path %>" class="text-gray-800 text-sm font-semibold border px-4 py-1 rounded-lg hover:text-purple-600 hover:border-purple-600">Sign up</a>
            </div>
        </div>
        </div>
    </div>
</div>

app/views/layouts/_notification.html.erb
<% if notice %>
  <div class="p-2 text-center">
    <div class="inline-flex items-center bg-white leading-none text-purple-600 rounded-full p-2 shadow text-teal text-sm">
      <span class="inline-flex bg-indigo-600 text-white rounded-full h-6 px-3 justify-center items-center">Notification</span>
      <span class="inline-flex px-2"><%= notice %> </span>
    </div>
  </div>
<% end %>

<% if alert %>
    <div class="p-2 text-center">
    <div class="inline-flex items-center bg-white leading-none text-pink-600 rounded-full p-2 shadow text-teal text-sm">
      <span class="inline-flex bg-pink-600 text-white rounded-full h-6 px-3 justify-center items-center">Error</span>
      <span class="inline-flex px-2"><%= alert %></span>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Management </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag    'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="bg-gray-100 font-sans w-full min-h-screen m-0">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/notification'%>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>